# Generated by Django 5.0.1 on 2024-01-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_forms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forms',
            options={'verbose_name': 'Murojat', 'verbose_name_plural': 'Murojatlar'},
        ),
    ]
